data:
  resting: ./data/raw/ds004504
  photic: ./data/raw/ds006036

experiment:
  binary_classification: true
  n_splits: 5
  seed: 42
  max_subjects: 10

model:
  type: "detach_rocket"
  params:
    num_kernels: 1000
    num_models: 5