name: TaskEEG-Dx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mne
      - numpy
      - pandas
      - PyYAML
      - scikit-learn
      - scipy
      - matplotlib
      - eegdash
      - pyts
      - torch
      - sktime==0.30.0
      - git+https://github.com/gon-uri/detach_rocket
